### ISSUE TITLE
Bindings todo list

### ISSUE THREAD

**Issue by novakne** [swaywm/zig-wlroots#15]
It would be great to quickly see what's still missing
Comparing with wlroots repo, that's what I saw, I probably missed some, maybe there is some that are not needed or some that would be great to make in priority, so feel free to correct me
- [ ] [wlr_fullscreen_shell_v1](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_fullscreen_shell_v1.h) - Done in #23, but would require unwanted changes in river  for now, so  if you have an use case and need it, please let us now it in the open PR
- [x] [wlr_input_method_v2](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_input_method_v2.h)
- [x] [wlr_keyboard_shortcuts_inhibit_v1](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_keyboard_shortcuts_inhibit_v1.h)
- [x] [wlr_presentation_time](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_presentation_time.h)
- [ ] [wlr_region](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_region.h)
- ~~[wlr_server_decoration](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_server_decoration.h)~~ obsolete
- [x] [wlr_switch](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_switch.h)
- [ ] [wlr_tablet_pad](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_tablet_pad.h)
- [ ] [wlr_tablet_v2](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_tablet_v2.h)
- [x] [wlr_text_input_v3](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_text_input_v3.h)
- [ ] [wlr_xdg_foreign_registry](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_xdg_foreign_registry.h)
- [ ] [wlr_xdg_foreign_v2](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_xdg_foreign_v2.h)

**Comment by ifreund** [comment]
So far I've personally only written bindings that I need for river or that were blocking someone else from contributing to river and don't plan on changing that. However, if you or others want to start working towards more complete bindings I'm happy to continue to review and merge patches as my time permits.

**Comment by novakne** [comment]
Fair enough, I was reading the futur protocol xdg_activation that I found interesting, and try to make it for zig to learn (I know it's not for now) so maybe I will make some other if I got time

**Comment by HeavyRain266** [comment]
I will help with feeling this list because like tablet protocol is something that I would need in RoseQuartz 😀

**Comment by ifreund** [comment]
For anyone looking to contribute, my process so far has been running `zig translate-c` on the header I'm translating then copying the relative struct/function definitions to a new zig file. Then I clean up the output, improving types and adding wrappers where needed.

**Comment by novakne** [comment]
What command are you usually using for `zig translate-c`, I often have problem to make it works with all libraries?

**Comment by HeavyRain266** [comment]
> So far I've personally only written bindings that I need for river or that were blocking someone else from contributing to river and don't plan on changing that. However, if you or others want to start working towards more complete bindings I'm happy to continue to review and merge patches as my time permits.

Thats understandable, but by looking at other bindings, zig ones are only active ones mostly because of river but we can go a step further and zig bindings will become a great alternative to the C original. From my perspective, Zig bindings are much easier to use and better to read ompared to C and Kotlin/Native with cinterop bindings ...

**Comment by ifreund** [comment]
> What command are you usually using for `zig translate-c`, I often have problem to make it works with all libraries?

Something like this:
```
 zig translate-c /usr/include/wlr/types/wlr_surface.h -DWLR_USE_UNSTABLE -lwlroots -lpixman-1 -I /usr/include/pixman-1 > out.zig
 ```

**Comment by ifreund** [comment]
> Thats understandable, but by looking at other bindings, zig ones are only active ones mostly because of river but we can go a step further and zig bindings will become a great alternative to the C original. From my perspective, Zig bindings are much easier to use and better to read ompared to C and Kotlin/Native with cinterop bindings ...

I definitely agree that using wlroots from zig is even nicer than using it from C and far better than any other language I've seen so far. Completing these zig bindings is certainly desirable and river will probably require most of the TODO headers listed here as it becomes more feature-complete.

**Comment by HeavyRain266** [comment]
@novakne how are you testing those bindings from PRs? just add and then test compilation?

**Comment by novakne** [comment]
@HeavyRain266 Sorry I'm not sure to understand your question, are you talking about how I test the binding before opening a PR or like how the CI works?

**Comment by HeavyRain266** [comment]
@novakne testing bindings before you open PR.

**Comment by novakne** [comment]
@HeavyRain266 well currently there is no way to really test before, though if you wait for #29 you will be able to run `zig build test` and catch some errorrs

**Comment by novakne** [comment]
@HeavyRain266 you can now run `zig build test` to find errors or the CI gonna catch them anyway

**Comment by HeavyRain266** [comment]
@novakne Thanks for info.

**Comment by lambdadog** [comment]
Is `wlr_server_decoration` being removed from upstream wlroots? Because there are still usecases for it (applications which have not yet implemented xdg-decoration) and although I'm aware you've elected not to use it in River it seems opinionated for a wlroots binding to just decide not to bind it.

**Comment by novakne** [comment]
@lambdadog yes it is marked as [obsolete](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_server_decoration.h#L2) upstream, 3 years ago though, I am the one who removed it from this list, but note that I have no authority here and this is list is just to help a bit to see where we at.
As for binding it, someone could totally make a PR for it, and @ifreund would decide if it should be merged, wich make more sense if you have a real usecase in a project for it.

**Comment by lambdadog** [comment]
@novakne Ah, appreciated! I missed that.

It would certainly still be useful to have while https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2191 is still unmerged and undistributed, at the very least. I wouldn't be surprised if it still hasn't been removed despite being obsoleted specifically because it's still used by GTK.

Once I get to that point in implementing my compositor I'll likely open a PR for it, and I suppose we'll see what happens then.

**Comment by novakne** [comment]
Closing this, it is outdated and I have no motivation to update and maintain it up to date
